# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import client.src.data.proto_compiled.data.data_pb2 as data__pb2

class UserDataStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetUserData = channel.unary_unary(
                '/data.UserData/GetUserData',
                request_serializer=data__pb2.GetUserDataRequest.SerializeToString,
                response_deserializer=data__pb2.GetUserDataResponse.FromString,
                )
        self.AddUserData = channel.unary_unary(
                '/data.UserData/AddUserData',
                request_serializer=data__pb2.AddUserDataRequest.SerializeToString,
                response_deserializer=data__pb2.AddUserDataResponse.FromString,
                )
        self.UpdateUserData = channel.unary_unary(
                '/data.UserData/UpdateUserData',
                request_serializer=data__pb2.UpdateUserDataRequest.SerializeToString,
                response_deserializer=data__pb2.UpdateUserDataResponse.FromString,
                )
        self.DeleteUserData = channel.unary_unary(
                '/data.UserData/DeleteUserData',
                request_serializer=data__pb2.DeleteUserDataRequest.SerializeToString,
                response_deserializer=data__pb2.DeleteUserDataResponse.FromString,
                )


class UserDataServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetUserData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddUserData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateUserData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteUserData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserDataServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetUserData': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserData,
                    request_deserializer=data__pb2.GetUserDataRequest.FromString,
                    response_serializer=data__pb2.GetUserDataResponse.SerializeToString,
            ),
            'AddUserData': grpc.unary_unary_rpc_method_handler(
                    servicer.AddUserData,
                    request_deserializer=data__pb2.AddUserDataRequest.FromString,
                    response_serializer=data__pb2.AddUserDataResponse.SerializeToString,
            ),
            'UpdateUserData': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateUserData,
                    request_deserializer=data__pb2.UpdateUserDataRequest.FromString,
                    response_serializer=data__pb2.UpdateUserDataResponse.SerializeToString,
            ),
            'DeleteUserData': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteUserData,
                    request_deserializer=data__pb2.DeleteUserDataRequest.FromString,
                    response_serializer=data__pb2.DeleteUserDataResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'data.UserData', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class UserData(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetUserData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/data.UserData/GetUserData',
                                             data__pb2.GetUserDataRequest.SerializeToString,
                                             data__pb2.GetUserDataResponse.FromString,
                                             options, channel_credentials,
                                             insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AddUserData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/data.UserData/AddUserData',
                                             data__pb2.AddUserDataRequest.SerializeToString,
                                             data__pb2.AddUserDataResponse.FromString,
                                             options, channel_credentials,
                                             insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateUserData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/data.UserData/UpdateUserData',
                                             data__pb2.UpdateUserDataRequest.SerializeToString,
                                             data__pb2.UpdateUserDataResponse.FromString,
                                             options, channel_credentials,
                                             insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteUserData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/data.UserData/DeleteUserData',
                                             data__pb2.DeleteUserDataRequest.SerializeToString,
                                             data__pb2.DeleteUserDataResponse.FromString,
                                             options, channel_credentials,
                                             insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class ItemDataStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetItemList = channel.unary_unary(
                '/data.ItemData/GetItemList',
                request_serializer=data__pb2.GetItemListRequest.SerializeToString,
                response_deserializer=data__pb2.GetItemListResponse.FromString,
                )
        self.GetItem = channel.unary_unary(
                '/data.ItemData/GetItem',
                request_serializer=data__pb2.GetItemRequest.SerializeToString,
                response_deserializer=data__pb2.GetItemResponse.FromString,
                )


class ItemDataServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetItemList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ItemDataServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetItemList': grpc.unary_unary_rpc_method_handler(
                    servicer.GetItemList,
                    request_deserializer=data__pb2.GetItemListRequest.FromString,
                    response_serializer=data__pb2.GetItemListResponse.SerializeToString,
            ),
            'GetItem': grpc.unary_unary_rpc_method_handler(
                    servicer.GetItem,
                    request_deserializer=data__pb2.GetItemRequest.FromString,
                    response_serializer=data__pb2.GetItemResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'data.ItemData', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ItemData(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetItemList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/data.ItemData/GetItemList',
                                             data__pb2.GetItemListRequest.SerializeToString,
                                             data__pb2.GetItemListResponse.FromString,
                                             options, channel_credentials,
                                             insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/data.ItemData/GetItem',
                                             data__pb2.GetItemRequest.SerializeToString,
                                             data__pb2.GetItemResponse.FromString,
                                             options, channel_credentials,
                                             insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class MapDataStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetMapData = channel.unary_unary(
                '/data.MapData/GetMapData',
                request_serializer=data__pb2.GetMapDataRequest.SerializeToString,
                response_deserializer=data__pb2.GetMapDataResponse.FromString,
                )


class MapDataServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetMapData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MapDataServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetMapData': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMapData,
                    request_deserializer=data__pb2.GetMapDataRequest.FromString,
                    response_serializer=data__pb2.GetMapDataResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'data.MapData', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MapData(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetMapData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/data.MapData/GetMapData',
                                             data__pb2.GetMapDataRequest.SerializeToString,
                                             data__pb2.GetMapDataResponse.FromString,
                                             options, channel_credentials,
                                             insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
