# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: player_pos.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10player_pos.proto\x12\nplayer_pos\";\n\nPosWrapper\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x1c\n\x03pos\x18\x02 \x01(\x0b\x32\x0f.player_pos.Pos\"`\n\x03Pos\x12\r\n\x05pos_x\x18\x01 \x01(\x04\x12\r\n\x05pos_y\x18\x02 \x01(\x04\x12\x12\n\nvelocity_x\x18\x03 \x01(\x04\x12\x12\n\nvelocity_y\x18\x04 \x01(\x04\x12\x13\n\x0blast_update\x18\x05 \x01(\x04\"/\n\rGetPosRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\r\n\x05token\x18\x02 \x01(\t\"?\n\x0eGetPosResponse\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x1c\n\x03pos\x18\x02 \x01(\x0b\x32\x0f.player_pos.Pos\"P\n\x10UpdatePosRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\r\n\x05token\x18\x02 \x01(\t\x12\x1c\n\x03pos\x18\x03 \x01(\x0b\x32\x0f.player_pos.Pos\"$\n\x11UpdatePosResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"2\n\x10GetAllPosRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\r\n\x05token\x18\x02 \x01(\t\"8\n\x11GetAllPosResponse\x12#\n\x03pos\x18\x01 \x03(\x0b\x32\x16.player_pos.PosWrapper2\xf9\x01\n\x10PlayerPosService\x12\x45\n\x0cPlayerGetPos\x12\x19.player_pos.GetPosRequest\x1a\x1a.player_pos.GetPosResponse\x12N\n\x0fPlayerUpdatePos\x12\x1c.player_pos.UpdatePosRequest\x1a\x1d.player_pos.UpdatePosResponse\x12N\n\x0fPlayerGetAllPos\x12\x1c.player_pos.GetAllPosRequest\x1a\x1d.player_pos.GetAllPosResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'player_pos_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_POSWRAPPER']._serialized_start=32
  _globals['_POSWRAPPER']._serialized_end=91
  _globals['_POS']._serialized_start=93
  _globals['_POS']._serialized_end=189
  _globals['_GETPOSREQUEST']._serialized_start=191
  _globals['_GETPOSREQUEST']._serialized_end=238
  _globals['_GETPOSRESPONSE']._serialized_start=240
  _globals['_GETPOSRESPONSE']._serialized_end=303
  _globals['_UPDATEPOSREQUEST']._serialized_start=305
  _globals['_UPDATEPOSREQUEST']._serialized_end=385
  _globals['_UPDATEPOSRESPONSE']._serialized_start=387
  _globals['_UPDATEPOSRESPONSE']._serialized_end=423
  _globals['_GETALLPOSREQUEST']._serialized_start=425
  _globals['_GETALLPOSREQUEST']._serialized_end=475
  _globals['_GETALLPOSRESPONSE']._serialized_start=477
  _globals['_GETALLPOSRESPONSE']._serialized_end=533
  _globals['_PLAYERPOSSERVICE']._serialized_start=536
  _globals['_PLAYERPOSSERVICE']._serialized_end=785
# @@protoc_insertion_point(module_scope)
